version: "0.2"
ignorePaths:
  - "build/**"
  - "components/**"
  - "assessments/**"
  - "finopspp.egg-info/**"
  - "tools/scratch/**"
  - "pyproject.toml"
words:
  - "finopspp"
  - "quigley"
  - "prasshant"
  - "sharrma"
  - "pydantic"
  - "collab"
  - "itam"
  - 'gamify'
  - "venv"
  - "pylint"
  - "pylintrc"
  - "pyproject"
  - "pymarkdownlnt"
  - "byol"
  - "secho"
  - "sumif"
  - "pyml"
  - "rarr"
  - "xlsxwriter"
  - "rcfile"
allowCompoundWords: true
